version: '2'
services:
  server:
    image: yywing/cve-2022-0778-target
    command: ["python", "server.py"]
    ports:
      - "12345:12345"
  badserver:
    image: yywing/cve-2022-0778
    command: ["--addr", "0.0.0.0:12346"]
    ports:
      - "12346:12346"
